import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>GlycoHeritage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-slate-800'>
        <h1 className=' italic bg-red-400'>asdadad</h1>
      </main>
    </>
  )
}
