import Head from 'next/head'
import HomePage from './home'
import Figma from '@/components/Figma'
import glycoHeritage from '../public/glycoheritage-logo-removebg-preview.png'
import Image from 'next/image'
import ComingSoon from '@/components/ComingSoon'
export default function Home() {
  return (
    <>
      <Head>
        <title>GlycoHeritage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main >
        {/* <Figma /> */}
        <div className='flex sm:flex-row sm:px-2 flex-col  px-5 items-center justify-between'>
          <div >
            <Image src={glycoHeritage} alt="logo" />
          </div>
          <div>
            <ComingSoon />
          </div>
        </div>
      </main>
    </>
  )
}
